@baseUrl = http://localhost/extracker/backend
@contentType = application/json


POST {{baseUrl}}/auth.php
Content-Type: {{contentType}}

{
"action":"register",
"username":"salam",
"password":"humbet2",
"confirmPassword":"humbet2"
}